package com.indiestream.infrastructure.seeder.service;

import com.indiestream.infrastructure.seeder.util.LocalMultipartFile;
import com.indiestream.playlist.PlaylistDto;
import com.indiestream.playlist.api.PlaylistModuleApi;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Slf4j
@Service
@Profile("seeder")
@RequiredArgsConstructor
public class PlaylistSeederService {

    // Injecting the REAL service so that domain events (TrackAddedToPlaylistEvent)
    // are naturally fired, triggering the PlaylistCentroidWorker to calculate V_playlist.
    private final PlaylistModuleApi playlistModuleApi;
    private final Random random = new Random();

    private static final String[] PLAYLIST_ADJECTIVES = {"Vibes", "Mix", "Essentials", "Daily", "Focus", "Chill", "Energy"};
    private static final String SEED_DATA_DIR = "./seed-data/";
    private static final String COVERS_DIR_NAME = "covers";

    public void seedPlaylists(List<UUID> listenerIds, List<UUID> trackIds) {
        log.info("--- PHASE 3.5: SEEDING SOCIAL PLAYLISTS ---");

        if (listenerIds.isEmpty() || trackIds.isEmpty()) {
            log.warn("Missing users or tracks. Aborting Playlist Seeding.");
            return;
        }

        List<Path> availableCovers = loadCoverImages();

        int playlistsCreated = 0;
        int tracksAdded = 0;

        for (UUID listenerId : listenerIds) {
            // Each listener creates 1 to 3 playlists
            int playlistCount = random.nextInt(3) + 1;

            for (int i = 0; i < playlistCount; i++) {
                try {
                    String name = "Seed " + PLAYLIST_ADJECTIVES[random.nextInt(PLAYLIST_ADJECTIVES.length)] + " " + (i + 1);

                    // 1. Create Playlist via Service
                    PlaylistDto playlist = playlistModuleApi.createCustomPlaylist(listenerId, name, "Generated by Seeder", true, false);
                    playlistsCreated++;

                    // 2. Set Cover if available
                    if (!availableCovers.isEmpty()) {
                        Path randomCoverPath = availableCovers.get(random.nextInt(availableCovers.size()));
                        String contentType = determineImageContentType(randomCoverPath);
                        LocalMultipartFile coverFile = new LocalMultipartFile("file", contentType, randomCoverPath);
                        playlistModuleApi.updatePlaylistCover(playlist.id(), listenerId, coverFile);
                    }

                    // 3. Add random tracks
                    int tracksToPopulate = random.nextInt(10) + 5;
                    List<UUID> shuffledTracks = new ArrayList<>(trackIds);
                    Collections.shuffle(shuffledTracks);

                    List<UUID> selectedTracks = shuffledTracks.subList(0, Math.min(tracksToPopulate, shuffledTracks.size()));

                    for (UUID trackId : selectedTracks) {
                        // Trigger the event that recalculates the Centroid Vector.
                        playlistModuleApi.addTrackToPlaylist(playlist.id(), trackId, listenerId);
                        tracksAdded++;
                    }

                } catch (Exception e) {
                    log.error("Failed to seed playlist for listener {}: {}", listenerId, e.getMessage());
                }
            }
        }

        log.info("Social Playlists Seeded. Created {} playlists with {} total tracks.", playlistsCreated, tracksAdded);
        log.info("V_playlist vectors are currently being calculated asynchronously by PlaylistCentroidWorker.");
    }

    private List<Path> loadCoverImages() {
        Path coversDir = Paths.get(SEED_DATA_DIR).resolve(COVERS_DIR_NAME);
        if (!Files.exists(coversDir) || !Files.isDirectory(coversDir)) {
            log.info("No covers directory found at {}. Playlists will be seeded without covers.", coversDir);
            return Collections.emptyList();
        }

        try (Stream<Path> files = Files.list(coversDir)) {
            return files.filter(p -> {
                String name = p.toString().toLowerCase();
                return name.endsWith(".jpg") || name.endsWith(".jpeg") || name.endsWith(".png") || name.endsWith(".webp");
            }).collect(Collectors.toList());
        } catch (IOException e) {
            log.error("Failed to read covers directory. Seeding will proceed without covers.", e);
            return Collections.emptyList();
        }
    }

    private String determineImageContentType(Path path) {
        String name = path.toString().toLowerCase();
        if (name.endsWith(".png")) return "image/png";
        if (name.endsWith(".webp")) return "image/webp";
        return "image/jpeg";
    }
}