package com.indiestream.telemetry.controller;

import com.indiestream.media.api.MediaModuleApi;
import com.indiestream.telemetry.config.TelemetryCacheTemplate;
import com.indiestream.telemetry.dto.SimulationReportDto;
import com.indiestream.telemetry.service.TelemetrySimulatorService;
import com.indiestream.telemetry.worker.TimeWindowRollupWorker;
import lombok.RequiredArgsConstructor;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.Map;
import java.util.UUID;

/**
 * Administrative API for system testing, manual rollups, and traffic simulation.
 * Guarded strictly by ROLE_ADMIN.
 */
@RestController
@RequestMapping("/api/v1/admin/telemetry")
@RequiredArgsConstructor
@PreAuthorize("hasRole('ADMIN')")
public class TelemetryAdminController {

    private final TimeWindowRollupWorker rollupWorker;
    private final TelemetrySimulatorService simulatorService;
    private final MediaModuleApi mediaModuleApi;
    private final TelemetryCacheTemplate cacheTemplate;

    /**
     * Executes aggregation for a specific timeframe.
     * If bounds are omitted, defaults to processing the last 24 hours.
     */
    @PostMapping("/rollup/hourly/force")
    public ResponseEntity<Map<String, Integer>> forceHourlyRollup(
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime start,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime end) {

        cacheTemplate.evictByPrefix("analytics:historical:");

        OffsetDateTime effectiveEnd = end != null ? end : OffsetDateTime.now(ZoneOffset.UTC).plusHours(1).truncatedTo(ChronoUnit.HOURS);
        OffsetDateTime effectiveStart = start != null ? start : effectiveEnd.minusHours(24).truncatedTo(ChronoUnit.HOURS);

        Map<String, Integer> result = rollupWorker.executeHourlyRollup(effectiveStart, effectiveEnd, true);
        return ResponseEntity.ok(result);
    }

    /**
     * Executes daily compression for a specific timeframe.
     * Defaults to the last 48 hours.
     */
    @PostMapping("/rollup/daily/force")
    public ResponseEntity<String> forceDailyRollup(
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime start,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime end) {

        cacheTemplate.evictByPrefix("analytics:historical:");

        OffsetDateTime effectiveEnd = end != null ? end : OffsetDateTime.now(ZoneOffset.UTC);
        OffsetDateTime effectiveStart = start != null ? start : effectiveEnd.minusDays(2).truncatedTo(ChronoUnit.DAYS);

        int rows = rollupWorker.executeDailyRollup(effectiveStart, effectiveEnd, true);
        return ResponseEntity.ok("Daily Rollup executed (" + effectiveStart + " to " + effectiveEnd + "). " + rows + " tracks compressed.");
    }

    /**
     * RECONCILIATION ENDPOINT.
     * Syncs the public UI counters on tracks with the exact analytical sums from the warehouse.
     * Run this AFTER forcing a Daily Rollup or purging shadow traffic.
     */
    @PostMapping("/sync-totals")
    public ResponseEntity<String> synchronizePublicCounters() {
        cacheTemplate.evictByPrefix("analytics:historical:");

        int updatedTracks = mediaModuleApi.synchronizeTrackCountersWithTelemetry();
        return ResponseEntity.ok("Successfully synchronized counters for " + updatedTracks + " tracks from historical telemetry.");
    }

    /**
     * Generates extremely detailed synthetic telemetry traffic for E2E dashboard testing.
     * Uses "IndieStream-E2E-Simulator" User-Agent for easy SQL deletion later.
     *
     * @param playbacks Number of playback events to simulate.
     */
    @PostMapping("/seed")
    public ResponseEntity<SimulationReportDto> seedShadowTraffic(
            Principal principal,
            @RequestParam(defaultValue = "1000") int playbacks,
            @RequestParam(required = false) String trackName,
            @RequestParam(required = false) String playlistName) {

        UUID adminId = UUID.fromString(principal.getName());
        SimulationReportDto report = simulatorService.generateShadowTraffic(playbacks, adminId, trackName, playlistName);

        return ResponseEntity.ok(report);
    }

    /**
     * Purges synthetic telemetry generated by the /seed endpoint.
     */
    @DeleteMapping("/seed")
    @CacheEvict(value = "analytics:historical", allEntries = true)
    public ResponseEntity<String> purgeShadowTraffic(
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime start,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime end) {

        int deletedRows = simulatorService.purgeShadowTraffic(start, end);
        return ResponseEntity.ok("Successfully purged " + deletedRows + " E2E simulation records.");
    }
}