/**
 * Zero-dependency IndexedDB wrapper.
 * Provides offline-first idempotency for telemetry events to guarantee delivery
 * even if the user loses network connection or closes the tab abruptly.
 */

const DB_NAME = 'IndieStreamTelemetryDB';
const DB_VERSION = 1;

export const STORES = {
    PLAYBACK: 'unsent_playback',
    INTERACTION: 'unsent_interactions'
} as const;

export type StoreName = typeof STORES[keyof typeof STORES];

/**
 * Initializes the IndexedDB database and creates object stores if they do not exist.
 */
const initDB = (): Promise<IDBDatabase> => {
    return new Promise((resolve, reject) => {
        const request = indexedDB.open(DB_NAME, DB_VERSION);

        request.onupgradeneeded = (event) => {
            const db = (event.target as IDBOpenDBRequest).result;

            // Primary key is the UUID generated by the client
            if (!db.objectStoreNames.contains(STORES.PLAYBACK)) {
                db.createObjectStore(STORES.PLAYBACK, {keyPath: 'eventId'});
            }
            if (!db.objectStoreNames.contains(STORES.INTERACTION)) {
                db.createObjectStore(STORES.INTERACTION, {keyPath: 'eventId'});
            }
        };

        request.onsuccess = (event) => resolve((event.target as IDBOpenDBRequest).result);
        request.onerror = (event) => reject((event.target as IDBOpenDBRequest).error);
    });
};

/**
 * Saves a single telemetry payload to the specified store.
 */
export const saveEvent = async <T extends { eventId: string }>(storeName: StoreName, event: T): Promise<void> => {
    const db = await initDB();
    return new Promise((resolve, reject) => {
        const transaction = db.transaction(storeName, 'readwrite');
        const store = transaction.objectStore(storeName);
        const request = store.put(event);

        request.onsuccess = () => resolve();
        request.onerror = (e) => reject((e.target as IDBRequest).error);
    });
};

/**
 * Retrieves all pending telemetry events from the specified store.
 */
export const getPendingEvents = async <T>(storeName: StoreName): Promise<T[]> => {
    const db = await initDB();
    return new Promise((resolve, reject) => {
        const transaction = db.transaction(storeName, 'readonly');
        const store = transaction.objectStore(storeName);
        const request = store.getAll();

        request.onsuccess = () => resolve(request.result);
        request.onerror = (e) => reject((e.target as IDBRequest).error);
    });
};

/**
 * Deletes a batch of successfully transmitted events to prevent duplicate processing.
 */
export const deleteEvents = async (storeName: StoreName, eventIds: string[]): Promise<void> => {
    if (eventIds.length === 0) return;

    const db = await initDB();
    return new Promise((resolve, reject) => {
        const transaction = db.transaction(storeName, 'readwrite');
        const store = transaction.objectStore(storeName);

        eventIds.forEach(id => store.delete(id));

        transaction.oncomplete = () => resolve();
        transaction.onerror = (e) => reject((e.target as IDBRequest).error);
    });
};